#!/usr/bin/env php
<?php

use StoryblokLens\Commands\CheckCommand;
use StoryblokLens\Commands\InspectCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

/**
 * Start the console application.
 */
$app = new Application('Sb Lens', '1.0.x');
//$app->setDefaultCommand("build");


$app->add(new InspectCommand());
$app->add(new CheckCommand());
$app->run();